[package]
name = "filez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota = "0.2.3"

[dependencies.crosscurses]
version = "0.1"
features = ["win32"]
